## name of the workflow
name: workflow_mle_e2e_2_inference

## when the workflow action would be taken
on:
  ## the following is for 'at xx:40 mins for each hour each day'
  # schedule:
  #   - cron: '40 * * * *'
  ## the following is for 'at completion of some other workflow action this would trigger the current workflow action'
  # workflow_run:
  #   workflows: ["covid1-modeltrainingpipeline"]
  #   types: 
  #     - completed
  ## the following is for 'at manual trigger from the github workflows'
  workflow_dispatch:

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Create directories
      run: |
        mkdir -p inputs
        mkdir -p models
        mkdir -p outputs

    - name: execute python workflows from bash script
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: jupyter nbconvert --to notebook --execute script_3_inference.ipynb
